
# The platform that we are building on. We only consider two, linux, or windows.
def build_platform
  RUBY_PLATFORM =~ /linux/ ? "linux" : "win"
end

# The build architecture is always x64 for now.
def build_arch
  "x64"
end

# Currently working off of github.com/mono/CppSharp/master at commit 0da9c46a7365be7d8b35a60ca4f822b6cbba6a49
def cpp_sharp_home
  ENV["CPPSHARP_HOME"] || (build_platform == "linux" ? "#{ENV["HOME"]}/src/CppSharp" : "/devel/src/CppSharp")
end

def cpp_sharp_cli_exe
  ENV["CPPSHARP_CLI_EXE"] ||
       (build_platform == "linux" ? "#{cpp_sharp_home}/build/gmake/lib/Release_x64/CppSharp.CLI.exe"
                                  : "#{cpp_sharp_home}/build/vs2017/lib/Release_x64/CppSharp.CLI.exe")
end


# This method produces the CppSharp CLI command
# for bash(linux) or cmd(windows) as we have to run on the build platform.
def cpp_sharp_cli
  if build_platform =~ /linux/
    # On linux CppSharp is made with gmake, and we must use mono.
    cli = "mono #{cpp_sharp_cli_exe}"
  else
    # On Windows CppSharp is built with vs2017 natively.
    cli = "#{cpp_sharp_cli_exe}"
  end
  cli
end

def cpp_sharp_check(verbose)
    if !File.exists?(cpp_sharp_cli_exe)
       puts "The location of CPPSHARP_CLI_EXE does not exist. Current value: #{cpp_sharp_cli_exe}"
       puts "Please set CPPSHARP_CLI_EXE or CPPSHARP_HOME."
       if !File.exists?(cpp_sharp_home)
           puts "Current CPPSHARP_HOME is #{cpp_sharp_home} and it does not exist" if cpp_sharp_home
       end
       false
    else
      if verbose
          puts "CPPSHARP_CLI_EXE: #{cpp_sharp_cli_exe}"
          puts "Using Cpp Sharp Command (platform:#{build_platform}): #{cpp_sharp_cli}"
      end
      true
    end
end

task :check do
  cpp_sharp_check(true)
end

task :cpp_sharp_check do
  if !cpp_sharp_check(false)
    exit 1
  end
end

def writeFile(file, content)
  fd = File.open(file, "w+")
  fd.write(content)
  fd.close
end

def generate(output_dir, platform, arch, files)
  dest = "#{output_dir}/#{platform}/#{arch}"
  sh gencmd(output_dir, platform, arch, files)
end

task :fix_string_val => ["Generated/#{build_platform}/#{build_arch}/ALK/ALK.cs"] do
  puts "Fixing std._String_val"
  fixed = fixStringVal(build_platform, "Generated/#{build_platform}/#{build_arch}/ALK/Std.cs")
  if fixed
      puts "File String_val: done."
  else
      puts "No String_val fix needed: Linux"
  end
end

##
## Change the Std.StringVal FieldOffsets
##   [FieldOffset(0)]  ==> [FieldOffset(8)]
##   [FieldOffset(16)] ==> [FieldOffset(24)]
##   [FieldOffset(24)] ==> [FieldOffset(0)]
##
def getStringVal(file)
    content = File.read(file)
    content.match(/namespace StringVal[\s][^}]*}[\s][^}]*}[\s][^}]*}\s*}/).to_s
end

def replaceStringVal(file, new_content)
    content = File.read(file)
    content.sub!(/namespace StringVal[\s][^}]*}[\s][^}]*}[\s][^}]*}\s*}/, new_content)
    writeFile(file, content)
end

def fixStringVal(platform, file)
  if platform == "win"
      content = getStringVal(file)
      # order is important
      content = content.sub("FieldOffset(0)", "FieldOffset(8)")
                       .sub("FieldOffset(24)", "FieldOffset(0)")
                       .sub("FieldOffset(16)", "FieldOffset(24)")
      replaceStringVal(file, content)
      true
  end
end

##
## Change the Test Class FieldOffsets
##   [FieldOffset(0)]  ==> [FieldOffset(0)]
##   [FieldOffset(32)] ==> [FieldOffset(40)]
##   [FieldOffset(64)] ==> [FieldOffset(80)]
##   [FieldOffset(96)] ==> [FieldOffset(120)]
##
def getTestClass(file)
  content = File.read(file)
  content.match(/public unsafe partial class Test(\s*[^}])*}/).to_s
end

def replaceTestClass(file, new_content)
  content = File.read(file)
  content.sub!(/public unsafe partial class Test(\s*[^}])*}/, new_content)
  writeFile(file, content);
end

def fixTestClass(platform, file)
  if platform == "win"
      content = getTestClass(file)
      content = content.sub("FieldOffset(32)", "FieldOffset(40)")
                       .sub("FieldOffset(64)", "FieldOffset(80)")
                       .sub("FieldOffset(96)", "FieldOffset(120)")
      replaceTestClass(file, content)
      true
  end
end

# only for windows
task :fix_test_class => ["Generated/#{build_platform}/#{build_arch}/ALK/ALK.cs"] do
  puts "Fixing Test class Field Offsets"
  fixed = fixTestClass(build_platform, "Generated/#{build_platform}/#{build_arch}/ALK/ALK.cs")
  if fixed
      puts "File Test Class FieldOffsets: done."
  else
      puts "No String_val fix needed."
  end
end

task :fix => [:fix_test_class, :fix_string_val]

def gencmd(output_dir, platform, arch, files)
    vector_holder_path = File.expand_path("CppAPI/Interop/VectorHolder.hpp")
    optional_path = File.expand_path("CppAPI/Interop/Optional.hpp")

    options = "-DGENERATE"
    cflags = " -std=c++11 -D_DEBUG"
    #
    # We are just going with options at this point. CFlags don't mean much here.
    #
    dest = "#{output_dir}/#{platform}/#{arch}/ALK"
    cmd = "#{cpp_sharp_cli} "
    if platform == "linux"
      cmd << "--c++11 "
    end
    cmd << "--A=\"#{cflags}\""
    cmd << "--p=#{platform} --a=#{arch} "
    cmd << "--on=ALK "                                             # Output namespace
    cmd << "--o=#{dest} "                                          # output directory for generated files
    cmd << options << " "                                          # Compiler Options from above.
    cmd << files.join(" ")                                         # Include files
    cmd
end

directory("Generated")

file "Generated/#{build_platform}/#{build_arch}/ALK/ALK.cs" => [:cpp_sharp_check] + FileList["Generated", "Includes.hpp", "CppAPI/**/*.hpp"] do
    generate("Generated", build_platform, build_arch, ["Includes.hpp"])
end

desc "Generates the ALK.Interop.cs file and the symbols"
task :generate => ["Generated", "Generated/#{build_platform}/#{build_arch}/ALK/ALK.cs"]

task :gen => [:cpp_sharp_check, "Generated"] do
   generate("Generated", build_platform, build_arch, ["Includes.hpp"])
end

task :clean do
  rm_rf "cmake-#{build_platform}-build"
  rm_rf "Generated"
end

task :regen => [:clean, :gen]

directory("cmake-#{build_platform}-build")

file "cmake-linux-build/CMakeCache.txt" => ["cmake-linux-build", "CMakeLists.txt", "Generated/linux/#{build_arch}/ALK/ALK.cs"] do
  Dir.chdir("cmake-linux-build") do
    sh "cmake .."
  end
end

file "cmake-win-build/CMakeCache.txt" => ["cmake-win-build", "CMakeLists.txt", "Generated/win/#{build_arch}/ALK/ALK.cs"] do
  Dir.chdir("cmake-win-build") do
    # If it's not already built we build Debug.
    sh "cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .."
  end
end

file "bin/Debug/netcoreapp3.1/ALK.dll" => FileList["cmake-win-build/CMakeCache.txt", "CppAPI/**/*.?pp"] do
  Dir.chdir("cmake-win-build") do
    sh "ninja install"
  end
end

file "bin/Debug/netcoreapp3.1/libALK.so" => FileList["cmake-linux-build/CMakeCache.txt", "CppAPI/**/*.?pp"] do
  Dir.chdir("cmake-linux-build") do
    sh "make install"
  end
end

library = build_platform == "linux" ? "bin/Debug/netcoreapp3.1/libALK.so" : "bin/Debug/netcoreapp3.1/ALK.dll"

task :compile => [library]

task :run => [:compile] do
  sh "dotnet run"
end